<a href="https://colab.research.google.com/github/nguyenthaibaok5bt-png/THDeepLearning1/blob/main/THDeepLearningB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]


In [7]:
import numpy as np

c = np.array([(1, 2, 3),
              (4, 5, 6)
              ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [8]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [9]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n', e)
print('One matrix \n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3, 2)
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]\
              ])
print(g)
print(g.shape)
h = g.reshape(3, 4)
print('reshape (3, 4) \n', h)
j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2) \n', j)
k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2) \n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4) 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2) 
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2) 
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [13]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]\
              ])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [14]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h = np.hstack((f, g))
print('Horizontal Append \n', h)
i = np.vstack((f, g))
print('Vertical Append \n', i)

Horizontal Append 
 [1. 2. 3. 4. 5. 6.]
Vertical Append 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
a = np.random.randint(100, size=(1, 5))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)


Random 1-D array
 [[94 14 90 99 34]]
Random 2-D array
 [[ 4 19 41 94]
 [68  5 35 28]
 [15 41 41 50]]
Random 3-D array
 [[[62 77 89]
  [53  2 57]
  [35 73 81]
  [77 29 50]]

 [[71 75 97]
  [46 66  0]
  [70 22 52]
  [39 30 39]]

 [[42 85 13]
  [31 48 12]
  [92 88 14]
  [21 65 77]]]


In [19]:
a = np.random.rand(5)
print('Random 1-D array \n', a)
b = np.random.rand(3, 4)
print('Random 2-D array \n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array \n', c)

Random 1-D array 
 [0.75501789 0.45296654 0.80550105 0.78091997 0.88038032]
Random 2-D array 
 [[0.25864971 0.75199267 0.84119933 0.98794499]
 [0.03241863 0.70404511 0.56701858 0.16443828]
 [0.79105431 0.21646126 0.22509022 0.63186779]]
Random 3-D array 
 [[[3.03884742e-04 4.25206213e-01 4.73677170e-03]
  [9.79738932e-01 3.14747767e-01 7.87458849e-01]
  [9.56761064e-01 3.34947628e-01 2.99257277e-01]
  [5.44501326e-01 8.77095563e-01 3.12118444e-01]]

 [[3.62807521e-01 9.18850894e-01 9.82989387e-01]
  [4.82725561e-01 9.80454362e-01 8.68213550e-01]
  [7.14368184e-01 4.30179814e-01 6.65939889e-01]
  [5.62491688e-01 8.44737809e-01 6.41328337e-01]]

 [[6.27146657e-01 9.14979095e-01 1.28863542e-01]
  [6.49198054e-01 5.80271809e-01 2.51691489e-01]
  [5.96565164e-01 2.15355551e-01 6.21091876e-01]
  [8.76447089e-01 5.46304295e-01 9.72880230e-01]]]


In [21]:
a = np.random.normal(5, 0.5, 10)
print(a)

a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

[4.48072804 5.16177206 4.15880798 5.66104659 4.70697538 4.93965019
 4.30483396 5.79240799 5.0117329  5.94286276]
18
[[ 8 14 14  6 12]
 [20 18 10  4  8]
 [ 2  8  8 16  4]]


In [22]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)
np.array(A)[2] = 2
print('TChange values of third row with array', A)
np.asarray(A)[2] = 2
print('TChange values of third row with asarray', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
TChange values of third row with array [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
TChange values of third row with asarray [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
a = np.arange(1, 20)
print(a)

b = np.arange(1, 20, 2)
print(b)

a = np.linspace(1, 20, 10)
print(a)

b = np.linspace(1, 20, 10, endpoint=False)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]
[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]


In [24]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row: ', a[0])
print('second row: ', a[1])

print('second column: ', a[:, 1])
print('first column: ', a[:, 0])
print('first two values of second row: ', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row:  [1 2 3]
second row:  [4 5 6]
second column:  [2 5]
first column:  [1 4]
first two values of second row:  [4 5]


In [26]:
 import pandas as pd

 a = pd.Series([1., 2., 3.])
 print(a)
 print('First value: ', a[0])
 b = pd.Series([1., 2. ,3.], index=['a', 'b', 'c'])
 print(b)
 print('First value: ', b['a'])

 calories = {"day1": 420, "day2": 380, "day3": 390}
 myvar = pd.Series(calories)
 print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value:  1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value:  1.0
day1    420
day2    380
day3    390
dtype: int64


In [27]:
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h)

numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)


DataFrame: 
    0  1
0  1  2
1  3  4
Numpy array: 
 [[1 2]
 [3 4]]


In [28]:
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [29]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns = ['so1', 'so2', 'so3', 'so4'])
print(df.head())

        so1       so2       so3       so4
0 -1.264345  0.975182 -0.690579  0.724328
1  0.257722 -1.411924  0.273413 -0.887761
2 -0.836265  0.937726 -0.383978  0.064596
3 -1.286648 -0.104582  0.393809 -0.340771
4 -0.211227  2.072477  0.388389  1.443639


In [32]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns = ['so1', 'so2', 'so3', 'so4'])
print(df.head())
print('Chon cot so1\n', df['so1'])
print('Chon nhieu dong\n', df[0:3])
print('Chon nhieu cot\n', df[['so1', 'so3']])
print('Chon cot dong, nhieu cot\n', df.iloc[:3, :2])
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -0.171112  0.757224  0.478351  0.331716
1 -0.449363  1.508579 -0.189908  1.614172
2 -0.684845 -0.009410  1.109704  1.020858
3  1.706672 -1.401381 -1.206706  0.273752
4 -0.279481 -1.777915 -0.238900 -0.810378
Chon cot so1
 0    -0.171112
1    -0.449363
2    -0.684845
3     1.706672
4    -0.279481
5     0.842640
6     1.996545
7    -1.087073
8     0.296270
9    -0.212781
10    0.100108
11   -0.502507
12   -1.332090
13   -1.019551
14    0.164359
15   -2.082236
16   -0.314302
17    1.088671
18   -0.944580
19   -0.685608
Name: so1, dtype: float64
Chon nhieu dong
         so1       so2       so3       so4
0 -0.171112  0.757224  0.478351  0.331716
1 -0.449363  1.508579 -0.189908  1.614172
2 -0.684845 -0.009410  1.109704  1.020858
Chon nhieu cot
          so1       so3
0  -0.171112  0.478351
1  -0.449363 -0.189908
2  -0.684845  1.109704
3   1.706672 -1.206706
4  -0.279481 -0.238900
5   0.842640  1.000357
6   1.996545 -1.255923
7  -1.087073 -0.489420
